#!/bin/bash

# Fetch the list of contributors from Github, and render it in a HTML page to be included in the about dialog
# TODO Integrate this to the build pipeline

org=VinylMusicPlayer
repo=${org}/VinylMusicPlayer
maintainers_csv="app/src/main/assets/maintainers.csv"
contributors_csv="app/src/main/assets/contributors.csv"
credits_html="app/src/main/assets/credits.html"

function update_contributors_csv()
{
  gh api -H "Accept: application/vnd.github+json" "/repos/${repo}/contributors?per_page=10" \
    | jq -r '.[] | [.login,.avatar_url,.html_url,.contributions] | @csv'
}

function update_maintainers_csv()
{
  gh api -H "Accept: application/vnd.github+json" "/orgs/${org}/members?per_page=10" \
    | jq -r '.[] | [.login,.avatar_url,.html_url,.type] | @csv'
}

function update_credits_html()
{
  cat << HEADER
<html>
  <head><style>
    body {
      background-color: #%{background-color};
      color: #%{color};
    }
    .login {
      vertical-align: middle;
    }
    a.login {
      color: #%{link-color};
    }
    .avatar {
      border-radius: 50% !important;
      width: 38px;
      height: 38px;
      vertical-align: middle;
    }
  </style></head>
  <body>
HEADER

  cat << MAINTAINERS_PROLOGUE
    <h4>%{@string/maintainers}</h4>
MAINTAINERS_PROLOGUE

  cat "${maintainers_csv}" | while read -r line; do
    IFS=',' read -r -a tokens <<< "${line}"

    login="${tokens[0]}"
    avatar_url="${tokens[1]}"
    html_url="${tokens[2]}"

    unquoted_login="${login:1:$((${#login}-2))}"

    cat << MAINTAINER
    <span style="white-space:nowrap">
      <img class="avatar" src=${avatar_url} alt=${login}/>
      <a class="login" href=${html_url}>${unquoted_login}</a>
    </span>
MAINTAINER
  done

  cat << CONTRIBUTORS_PROLOGUE
    <hr/>
    <h4>%{@string/contributors}</h4>
CONTRIBUTORS_PROLOGUE

  cat "${contributors_csv}" | while read -r line; do
    IFS=',' read -r -a tokens <<< "${line}"

    login="${tokens[0]}"
    avatar_url="${tokens[1]}"
    html_url="${tokens[2]}"

    unquoted_login="${login:1:$((${#login}-2))}"

    cat << CONTRIBUTOR
    <span style="white-space:nowrap">
      <img class="avatar" src=${avatar_url} alt=${login}/>
      <a class="login" href=${html_url}>${unquoted_login}</a>
    </span>
CONTRIBUTOR
  done

  cat << CONTRIBUTORS_EPILOGUE
    <p>
      <a class="login" href="https://github.com/VinylMusicPlayer/VinylMusicPlayer/graphs/contributors">
        %{@string/label_other_contributors}
      </a>
    </p>
CONTRIBUTORS_EPILOGUE

  cat << SPECIAL_THANKS
    <hr/>
    <h4>%{@string/special_thanks_to}</h4>
    <span style="white-space:nowrap">
      <img class="avatar" src="https://avatars.githubusercontent.com/u/7303830?v=4" alt="kabouzeid"/>
      <a class="login" href="https://github.com/kabouzeid">%{@string/karim_abou_zeid}</a>
      <p>%{@string/karim_abou_zeid_summary}</p>
    </span>
    <span style="white-space:nowrap">
      <img class="avatar" src="https://avatars.githubusercontent.com/u/1820165?v=4" alt="afollestad"/>
      <a class="login" href="https://github.com/afollestad">%{@string/aidan_follestad}</a>
      <p>%{@string/aidan_follestad_summary}</p>
    </span>
    <span style="white-space:nowrap">
      <a class="login" href="https://cookicons.co/">%{@string/michael_cook_cookicons}</a>
      <p>%{@string/michael_cook_summary}</p>
    </span>
    <span style="white-space:nowrap">
      <a class="login" href="https://maartencorpel.com/">%{@string/maarten_corpel}</a>
      <p>%{@string/maarten_corpel_summary}</p>
    </span>
    <span style="white-space:nowrap">
      <a class="login" href="https://twitter.com/djsalezmaj">%{@string/aleksandar_tesic}</a>
      <p>%{@string/aleksandar_tesic_summary}</p>
    </span>
    <span style="white-space:nowrap">
      <img class="avatar" src="https://avatars.githubusercontent.com/u/4098258?v=4" alt="arkon"/>
      <a class="login" href="https://github.com/arkon">%{@string/eugene_cheung}</a>
      <p>%{@string/eugene_cheung_summary}</p>
    </span>
    <span style="white-space:nowrap">
      <a class="login" href="https://twitter.com/froschgames">%{@string/adrian}</a>
      <p>%{@string/adrian_summary}</p>
    </span>
SPECIAL_THANKS

  cat << FOOTER
  </body></html>
FOOTER
}

echo "Getting the list of maintainers from Github..."
update_maintainers_csv > ${maintainers_csv} || exit 1
echo "Getting the list of contributors from Github..."
update_contributors_csv > ${contributors_csv} || exit 1
echo "Building the contributor page in HTML..."
update_credits_html > ${credits_html} || exit 1
