#!/bin/bash

# Fetch the list of contributors from Github, and render it in a HTML page to be included in the about dialog
# TODO Integrate this to the build pipeline

repo=vinyl2-team/vinyl2
contributors_csv="app/src/main/assets/contributors.csv"
contributors_html="app/src/main/assets/contributors.html"

function update_contributors_csv()
{
  gh api -H "Accept: application/vnd.github+json" "/repos/${repo}/contributors?per_page=10" \
    | jq -r '.[] | [.login,.avatar_url,.html_url,.contributions] | @csv'
}

function update_contributors_html()
{
  cat << HEADER
<html>
  <head><style>
    body {
      background-color: #%{background-color};
      color: #%{color};
    }
    .contributor-login {
      vertical-align: middle;
    }
    a.contributor-login {
      color: #%{link-color};
    }
    .contributor-avatar {
      border-radius: 50% !important;
      width: 38px;
      height: 38px;
      vertical-align: middle;
    }
  </style></head>
  <body>
    <h4>%{@string/maintainers_and_contributors}</h4>
HEADER

  cat "${contributors_csv}" | while read -r line; do
    IFS=',' read -r -a tokens <<< "${line}"

    login="${tokens[0]}"
    avatar_url="${tokens[1]}"
    html_url="${tokens[2]}"

    unquoted_login="${login:1:$((${#login}-2))}"

    cat << CONTRIBUTOR
    <span style="white-space:nowrap">
      <img class="contributor-avatar" src=${avatar_url} alt=${login}/>
      <a class="contributor-login" href=${html_url}>${unquoted_login}</a>
    </span>
CONTRIBUTOR
  done
  cat << MORE_CONTRIBUTORS
    <p>
      <a class="contributor-login" href="https://github.com/VinylMusicPlayer/VinylMusicPlayer/graphs/contributors">
        %{@string/label_other_contributors}
      </a>
    </p>
MORE_CONTRIBUTORS

  cat << FOOTER
    <hr>
    <h4>%{@string/special_thanks_to}</h4>
    <span style="white-space:nowrap">
      <img class="contributor-avatar" src="https://avatars.githubusercontent.com/u/7303830?v=4" alt="kabouzeid"/>
      <a class="contributor-login" href="https://github.com/kabouzeid">%{@string/karim_abou_zeid}</a>
      <p>%{@string/karim_abou_zeid_summary}</p>
    </span>
    <span style="white-space:nowrap">
      <img class="contributor-avatar" src="https://avatars.githubusercontent.com/u/1820165?v=4" alt="afollestad"/>
      <a class="contributor-login" href="https://github.com/afollestad">%{@string/aidan_follestad}</a>
      <p>%{@string/aidan_follestad_summary}</p>
    </span>
    <span style="white-space:nowrap">
      <a class="contributor-login" href="https://cookicons.co/">%{@string/michael_cook_cookicons}</a>
      <p>%{@string/michael_cook_summary}</p>
    </span>
    <span style="white-space:nowrap">
      <a class="contributor-login" href="https://maartencorpel.com/">%{@string/maarten_corpel}</a>
      <p>%{@string/maarten_corpel_summary}</p>
    </span>
    <span style="white-space:nowrap">
      <a class="contributor-login" href="https://twitter.com/djsalezmaj">%{@string/aleksandar_tesic}</a>
      <p>%{@string/aleksandar_tesic_summary}</p>
    </span>
    <span style="white-space:nowrap">
      <img class="contributor-avatar" src="https://avatars.githubusercontent.com/u/4098258?v=4" alt="arkon"/>
      <a class="contributor-login" href="https://github.com/arkon">%{@string/eugene_cheung}</a>
      <p>%{@string/eugene_cheung_summary}</p>
    </span>
    <span style="white-space:nowrap">
      <a class="contributor-login" href="https://twitter.com/froschgames">%{@string/adrian}</a>
      <p>%{@string/adrian_summary}</p>
    </span>

  </body></html>
FOOTER
}

echo "Getting the list of contributors from Github..."
update_contributors_csv > ${contributors_csv} || exit 1
echo "Building the contributor page in HTML..."
update_contributors_html > ${contributors_html} || exit 1
