#!/bin/bash

# Fetch the list of maintainers/contributors from Github,
# and render it in a HTML page to be included in the about dialog

# to use: run this shell script from root of android project (before hand, `jq` and `gh` need to be installed in our system - be careful, gh need to be run once before to configure it properly)

org=VinylMusicPlayer
repo=${org}/VinylMusicPlayer
maintainers_csv="app/src/main/assets/maintainers.csv"
contributors_csv="app/src/main/assets/contributors.csv"
credits_html="app/src/main/assets/credits.html"

function update_contributors_csv()
{
  gh api -H "Accept: application/vnd.github+json" "/repos/${repo}/contributors?per_page=10" \
    | jq -r '.[] | [.login,.avatar_url,.html_url,.contributions] | @csv'
}

function update_maintainers_csv()
{
  gh api -H "Accept: application/vnd.github+json" "/orgs/${org}/members?per_page=10" \
    | jq -r '.[] | [.login,.avatar_url,.html_url,.type] | @csv'
}

function update_credits_html()
{
  cat << HEADER
<html>
  <head><style>
    body {
      background-color: #%{background-color};
      color: #%{color};
      padding: 0;
      margin: 0;
    }

    h4 {
      margin: %{margin}px;
      margin-top: %{title-top-margin}px;
      color: #%{title-color};
    }

    hr {
      border: 0;
      border: 0.5px solid #%{divider-color};
      margin: 0;
      padding: 0;
    }

    .big_link {
      padding: 0;
      width: 100%;
    }
    .big_link>a {
      text-decoration: none;
      color: #%{color};
    }
    .big_link>a>img {
      border-radius: 50% !important;
      width: 38px;
      height: 38px;
      float: left;
      padding: %{margin}px;
    }
    .big_link>a>.without_img {
      margin: 0;
      padding: 0;
      padding-left: %{margin}px;
      height: calc( 38px + %{margin}px );
    }
    .big_link>a>p {
      margin: 0;
      padding: 0;
      height: calc( 38px + 2 * %{margin}px );
      position: relative;
    }
    .big_link>a>p>span {
      position: absolute;
      top: 50%;
      transform: translate(0%, -50%);
    }
    .big_link>p {
      color: #%{secondary-text-color};
      font-size: 80%;
      padding-left: %{margin}px;
      padding-right: %{margin}px;
    }

    .small_link {
      padding: 0;
      display: inline-block;
    }
    .small_link>a {
      text-decoration: none;
      color: #%{color};
      display: inline-block;
      padding-left: %{margin}px;
      padding-right: %{margin}px;
    }
    .small_link>a>img {
      border-radius: 50% !important;
      width: 38px;
      height: 38px;
      vertical-align: middle;
      display: inline-block;
    }
    .small_link>a>p {
      vertical-align: middle;
      display: inline-block;
      padding: %{margin_4}px %{margin_2}px;
    }

    #others>a {
      padding-left: %{margin}px;
      padding-right: %{margin}px;
      color: #%{color};
      display: block;
      height: 38px;
      line-height: 38px;
    }
  </style></head>
  <body>
HEADER

  cat << MAINTAINERS_PROLOGUE
    <h4>%{@string/maintainers}</h4>
MAINTAINERS_PROLOGUE

  cat "${maintainers_csv}" | while read -r line; do
    IFS=',' read -r -a tokens <<< "${line}"

    login="${tokens[0]}"
    avatar_url="${tokens[1]}"
    html_url="${tokens[2]}"

    unquoted_login="${login:1:$((${#login}-2))}"

    cat << MAINTAINER
    <span class="small_link">
      <a href=${html_url}>
        <img src=${avatar_url} alt=${login}/>
        <p>${unquoted_login}</p>
      </a>
    </span>
MAINTAINER
  done

  cat << CONTRIBUTORS_PROLOGUE
    <hr/>
    <h4>%{@string/contributors}</h4>
CONTRIBUTORS_PROLOGUE

  cat "${contributors_csv}" | while read -r line; do
    IFS=',' read -r -a tokens <<< "${line}"

    login="${tokens[0]}"
    avatar_url="${tokens[1]}"
    html_url="${tokens[2]}"

    unquoted_login="${login:1:$((${#login}-2))}"

    cat << CONTRIBUTOR
    <span class="small_link">
      <a href=${html_url}>
        <img src=${avatar_url} alt=${login}/>
        <p>${unquoted_login}</p>
      </a>
    </span>
CONTRIBUTOR
  done

  cat << CONTRIBUTORS_EPILOGUE
    <p id="others">
      <a href="https://github.com/VinylMusicPlayer/VinylMusicPlayer/graphs/contributors">
        %{@string/label_other_contributors}
      </a>
    </p>
CONTRIBUTORS_EPILOGUE

  cat << SPECIAL_THANKS
    <hr/>
    <h4>%{@string/special_thanks_to}</h4>
    <div class="big_link">
      <a href="https://github.com/kabouzeid">
        <img src="https://avatars.githubusercontent.com/u/7303830?v=4" alt="kabouzeid"/>
        <p><span>%{@string/karim_abou_zeid}</span></p>
      </a>
      <p>%{@string/karim_abou_zeid_summary}</p>
    </div>
    <hr/>
    <div class="big_link">
      <a href="https://github.com/afollestad">
        <img src="https://avatars.githubusercontent.com/u/1820165?v=4" alt="afollestad"/>
        <p><span>%{@string/aidan_follestad}</span></p>
      </a>
      <p>%{@string/aidan_follestad_summary}</p>
    </div>
    <hr/>
    <div class="big_link">
      <a href="https://cookicons.co/">
        <p class="without_img"><span>%{@string/michael_cook_cookicons}</span></p>
      </a>
      <p>%{@string/michael_cook_summary}</p>
    </div>
    <hr/>
    <div class="big_link">
      <a href="https://maartencorpel.com/">
        <p class="without_img"><span>%{@string/maarten_corpel}</span></p>
      </a>
      <p>%{@string/maarten_corpel_summary}</p>
    </div>
    <hr/>
    <div class="big_link">
      <a href="https://twitter.com/djsalezmaj">
        <p class="without_img"><span>%{@string/aleksandar_tesic}</span></p>
      </a>
      <p>%{@string/aleksandar_tesic_summary}</p>
    </div>
    <hr/>
    <div class="big_link">
      <a href="https://github.com/arkon">
        <img src="https://avatars.githubusercontent.com/u/4098258?v=4" alt="arkon"/>
        <p><span>%{@string/eugene_cheung}</span></p>
      </a>
      <p>%{@string/eugene_cheung_summary}</p>
    </div>
    <hr/>
    <div class="big_link">
      <a href="https://twitter.com/froschgames">
        <p class="without_img"><span>%{@string/adrian}</span></p>
      </a>
      <p>%{@string/adrian_summary}</p>
    </div>
SPECIAL_THANKS

  cat << FOOTER
  </body></html>
FOOTER
}

echo "Getting the list of maintainers from Github..."
update_maintainers_csv > ${maintainers_csv} || exit 1
echo "Getting the list of contributors from Github..."
update_contributors_csv > ${contributors_csv} || exit 1
echo "Building the contributor page in HTML..."
update_credits_html > ${credits_html} || exit 1
